# Generated by Django 5.2 on 2025-05-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtovariacao',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, help_text='Se a variação está ativa/visível'),
        ),
    ]
