# Generated by Django 5.2 on 2025-04-28 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pedido_options_endereco_usuario_pedido_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='CEP deve estar no formato 12345-678', regex='^\\d{5}-\\d{3}$')]),
        ),
    ]
