# Generated by Django 5.2 on 2025-05-02 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250502_0317'),
    ]

    operations = [
    ]
