# Generated by Django 5.2 on 2025-05-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tamanhos',
        ),
    ]
