# Generated by Django 5.2 on 2025-04-29 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_endereco_options_endereco_atualizado_em_and_more'),
    ]

    operations = [
    ]
