# Generated by Django 5.2 on 2025-04-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250428_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tamanhos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanhos_disponiveis',
            field=models.CharField(blank=True, help_text='Tamanhos disponíveis separados por vírgula (ex: P,M,G)', max_length=50),
        ),
    ]
