# Generated by Django 5.2 on 2025-05-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_produto_tamanhos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cor',
        ),
        migrations.AddField(
            model_name='produto',
            name='cor_disponivel',
            field=models.CharField(blank=True, help_text='Cores disponíveis separadas por vírgula (ex: vermelho,azul,preto)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='dimensoes',
            field=models.CharField(blank=True, help_text='Dimensões do produto (ex: 30x20x10 cm)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Peso do produto em kg', max_digits=6, null=True),
        ),
    ]
