# Generated by Django 5.2 on 2025-05-02 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_produto_cor_produto_cor_disponivel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('valor_css', models.CharField(help_text="Valor para background-color no CSS (ex: 'red', '#ff0000')", max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cor_disponivel',
        ),
        migrations.CreateModel(
            name='ProdutoCor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cores', to='core.produto')),
            ],
            options={
                'unique_together': {('produto', 'cor')},
            },
        ),
    ]
