# Generated by Django 5.2 on 2025-04-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_produto_tamanhos_produto_tamanhos_disponiveis'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='tamanho',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
