# Generated by Django 5.2 on 2025-05-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_itempedido_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(default=1, editable=False, max_length=10, unique=True, verbose_name='Código do Pedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_rastreamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Rastreio'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Pagamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('E', 'Enviado'), ('T', 'Em Transporte'), ('C', 'Concluído'), ('X', 'Cancelado')], default='P', max_length=1),
        ),
    ]
