# Generated by Django 5.2 on 2025-05-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_marca_produto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='core.tag'),
        ),
    ]
