# Generated by Django 5.2 on 2025-05-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_produto_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='dimensoes',
        ),
        migrations.AddField(
            model_name='produto',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Altura em cm', null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='length',
            field=models.PositiveIntegerField(blank=True, help_text='Comprimento em cm', null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text='Largura em cm', null=True),
        ),
        migrations.AddField(
            model_name='produtovariacao',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Altura em cm', null=True),
        ),
        migrations.AddField(
            model_name='produtovariacao',
            name='length',
            field=models.PositiveIntegerField(blank=True, help_text='Comprimento em cm', null=True),
        ),
        migrations.AddField(
            model_name='produtovariacao',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Peso da variação em kg', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='produtovariacao',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text='Largura em cm', null=True),
        ),
    ]
