"""
Django settings for Projeto_Lukao project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega .env se existir
if os.path.exists(os.path.join(BASE_DIR, '.env')):
    from dotenv import load_dotenv
    load_dotenv()

# Acessa variáveis
SECRET_KEY = os.environ.get('SECRET_KEY')
DB_PASSWORD = os.environ.get('DB_PASSWORD')
MELHOR_ENVIO_TOKEN = os.environ.get('MELHOR_ENVIO_TOKEN')

MERCADO_PAGO_PUBLIC_KEY = os.getenv('MERCADO_PAGO_PUBLIC_KEY')
MERCADO_PAGO_ACCESS_TOKEN = os.getenv('MERCADO_PAGO_ACCESS_TOKEN')

STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY')
# Adicione esta linha - Obtenha o valor no Dashboard Stripe -> Developers -> Webhooks -> Seu Endpoint
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ==========================
# Configurações de Logging
# ==========================
import logging

class IgnoreCartCountFilter(logging.Filter):
    def filter(self, record):
        msg = str(record.getMessage())
        return '/api/cart/count/' not in msg

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'ignore_cart_count': {
            '()': IgnoreCartCountFilter,
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose' if DEBUG else 'simple',
            'filters': ['ignore_cart_count'],
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
            'filters': ['ignore_cart_count'],
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'] if DEBUG else ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'checkout': {
            'handlers': ['console', 'file'] if DEBUG else ['file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Cria diretório de logs se não existir
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)

# ==========================
# Configurações do Melhor Envio
# ==========================
MELHOR_ENVIO_BASE_URL = 'https://sandbox.melhorenvio.com.br/api/v2'  # Use 'https://melhorenvio.com.br/api/v2' em produção
MELHOR_ENVIO_CEP_ORIGEM = '59900-000'  # CEP da sua loja/origem

# Configurações do remetente para envios
REMETENTE_CONFIG = {
    'name': 'Lukao MultiMarcas',
    'phone': '(83)99381-0707',
    'email': 'lucas.sobreira@academico.ifpb.edu.br',
    'document': '00000000000',
    'company_document': '00000000000000',
    'state_register': '',
    'address': 'Rua Hipólito Cassiano',
    'complement': '',
    'number': '123',
    'district': 'Centro',
    'city': 'Pau dos Ferros',
    'state_abbr': 'RN',
    'country_id': 'BR',
    'postal_code': '59900-000'
}

# ==========================
# Configurações do Carrinho
# ==========================
CARRINHO_MAX_QUANTIDADE = 10  # Quantidade máxima por item no carrinho

# Configurações padrão para cálculo de frete
FRETE_DEFAULTS = {
    'peso_padrao': 1.0,  # kg
    'largura_padrao': 15,  # cm
    'altura_padrao': 10,  # cm
    'comprimento_padrao': 20,  # cm
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
# SECURITY WARNING: don't run with debug turned on in production!
# Already defined above
# DEBUG = True

ALLOWED_HOSTS = []
DEBUG = True

ALLOWED_HOSTS = []

LOGIN_URL = 'user:login'  # URL de login padrão
LOGIN_REDIRECT_URL = 'index'  # URL para redirecionar após o login
LOGOUT_REDIRECT_URL = 'user:login' # URL para redirecionar após o logout

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django_filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'user',
    'checkout',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Projeto_Lukao.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'core.context_processors.notificacoes_nao_lidas',
                'core.context_processors.endereco_do_usuario',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.categorias_e_tags',
            ],
        },
    },
]

WSGI_APPLICATION = 'Projeto_Lukao.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'site_lukao',
        'USER': 'postgres',
        'PASSWORD': DB_PASSWORD,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# AUTH_USER_MODEL = 'user.CustomUser'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = ''

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Garante que o diretório media exista
os.makedirs(MEDIA_ROOT, exist_ok=True)

# Configurações para os tipos de arquivos permitidos (opcional)
ALLOWED_FILE_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif', 'pdf']
MAX_UPLOAD_SIZE = 5242880  # 5MB

# Configuração de URLs para desenvolvimento
if DEBUG:
    # Serve arquivos de mídia durante o desenvolvimento
    from django.conf.urls.static import static
    urlpatterns = [
        # ... suas URLs existentes ...
    ] + static(MEDIA_URL, document_root=MEDIA_ROOT)
    
# # Configurações de E-mail
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'  # Exemplo: use seu provedor de e-mail
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'seu_email@gmail.com'  # Substitua pelo seu e-mail
# EMAIL_HOST_PASSWORD = 'sua_senha'  # Substitua pela sua senha ou app password
# DEFAULT_FROM_EMAIL = 'Loja de Roupas VSG <seu_email@gmail.com>'